default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>_development

test:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>_test

production:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>_development
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
